# Generated by Django 5.2.1 on 2026-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='site_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID no Site'),
        ),
    ]
