# Generated by Django 5.2.1 on 2026-06-08 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('tamanho', models.CharField(blank=True, max_length=20, verbose_name='Tamanho')),
                ('sku_variacao', models.CharField(max_length=80, unique=True, verbose_name='SKU da Variação')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('site_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID no Site')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produto',
                'ordering': ['cor', 'tamanho'],
                'unique_together': {('produto', 'cor', 'tamanho')},
            },
        ),
    ]
