# Generated by Django 5.2.1 on 2026-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_add_variacao_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_reservado',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, default='', verbose_name='URL da Imagem'),
        ),
    ]
