# Generated by Django 5.2.1 on 2026-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_sprint6_remove_slug_estoque_reservado_add_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=0, verbose_name='Estoque Mínimo'),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='estoque_minimo',
            field=models.IntegerField(default=0, verbose_name='Estoque Mínimo'),
        ),
    ]
