# Generated by Django 5.2.1 on 2026-06-05 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('site', 'Site'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('presencial', 'Presencial'), ('link', 'Link de Pagamento')], max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('reservado', 'Reservado'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('separacao', 'Em Separação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='orcamento', max_length=30, verbose_name='Status')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Bruto (R$)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto (R$)')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete (R$)')),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Líquido (R$)')),
                ('endereco_entrega', models.TextField(blank=True, verbose_name='Endereço de Entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Método')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LucroPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('receita_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita Bruta (R$)')),
                ('custo_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo dos Produtos (R$)')),
                ('taxa_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Pagamento (R$)')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete (R$)')),
                ('embalagem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Embalagem (R$)')),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Líquido (R$)')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lucro', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Lucro do Pedido',
                'verbose_name_plural': 'Lucros dos Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário (R$)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='produtos.produto', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
