# Generated by Django 5.2.1 on 2026-06-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_site_id'),
        ('produtos', '0003_add_variacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='produtos.variacaoproduto', verbose_name='Variação'),
        ),
    ]
