# Generated by Django 5.2.1 on 2026-06-09 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_add_endereco_cliente'),
        ('pedidos', '0003_add_variacao_to_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código de Rastreio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_estruturado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.enderecocliente', verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='previsao_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='url_rastreio',
            field=models.URLField(blank=True, verbose_name='URL de Rastreio'),
        ),
        migrations.CreateModel(
            name='EventoRastreio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_evento', models.DateTimeField(verbose_name='Data do Evento')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_rastreio', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Evento de Rastreio',
                'verbose_name_plural': 'Eventos de Rastreio',
                'ordering': ['-data_evento'],
            },
        ),
    ]
