# Generated by Django 5.2.1 on 2026-06-09 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_add_endereco_estruturado_to_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('reservado', 'Reservado'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('separacao', 'Em Separação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('troca_pendente', 'Troca Pendente'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='orcamento', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('reembolso', 'Reembolso'), ('troca', 'Troca'), ('credito', 'Crédito em Conta')], max_length=20, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('concluida', 'Concluída')], default='solicitada', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aprovada_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='pedidos.pedido', verbose_name='Pedido')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('condicao', models.CharField(choices=[('ok', 'Em bom estado'), ('defeito', 'Com defeito'), ('avaria', 'Avariado')], default='ok', max_length=20, verbose_name='Condição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.devolucao', verbose_name='Devolução')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_devolucao', to='pedidos.itempedido', verbose_name='Item do Pedido')),
            ],
            options={
                'verbose_name': 'Item de Devolução',
                'verbose_name_plural': 'Itens de Devolução',
            },
        ),
    ]
