# Generated by Django 5.2.1 on 2026-06-10 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_add_devolucao_itemdevolucao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nº de Parcelas'),
        ),
        migrations.CreateModel(
            name='ParcelaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Nº da Parcela')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=10, verbose_name='Status')),
                ('pago_em', models.DateField(blank=True, null=True, verbose_name='Pago em')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_parcela', to='pedidos.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['pagamento', 'numero'],
            },
        ),
    ]
