# Generated by Django 5.2.1 on 2026-06-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pagamento_parcelas_parcelapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('troca_pendente', 'Troca Pendente'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='orcamento', max_length=30, verbose_name='Status'),
        ),
    ]
