# Generated by Django 5.2.1 on 2026-06-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_categoriafinanceira_lancamentocaixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriafinanceira',
            name='pai',
        ),
    ]
