# Generated by Django 5.2.1 on 2026-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_sprint6_remove_categoriafinanceira_pai'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta de Faturamento (R$)')),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
