# Generated by Django 5.2.1 on 2026-06-11 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_add_meta_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentocaixa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.categoriafinanceira', verbose_name='Categoria'),
        ),
    ]
