# Generated by Django 5.2.1 on 2026-06-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamentocaixa_categoria_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
    ]
