# Generated by Django 5.2.1 on 2026-06-05 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('primeira_compra', models.DateField(blank=True, null=True, verbose_name='Primeira Compra')),
                ('ultima_compra', models.DateField(blank=True, null=True, verbose_name='Última Compra')),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Gasto (R$)')),
                ('qtd_pedidos', models.PositiveIntegerField(default=0, verbose_name='Qtd. Pedidos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
