# Generated by Django 5.2.1 on 2026-06-10 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_add_variacao_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao Fornecedor'), ('recebido_parcial', 'Recebido Parcialmente'), ('recebido', 'Recebido Completo'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (R$)')),
                ('previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Nº do Pedido')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='produtos.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário (R$)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='produtos.produto', verbose_name='Produto')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_compra', to='produtos.variacaoproduto', verbose_name='Variação')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra', verbose_name='Pedido de Compra')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens do Pedido de Compra',
            },
        ),
        migrations.CreateModel(
            name='RecebimentoMercadoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(verbose_name='Data do Recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.pedidocompra', verbose_name='Pedido de Compra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Recebimento de Mercadoria',
                'verbose_name_plural': 'Recebimentos de Mercadoria',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecebimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade_recebida', models.PositiveIntegerField(verbose_name='Qtd Recebida')),
                ('condicao', models.CharField(choices=[('ok', 'Ok'), ('avaria', 'Avariado')], default='ok', max_length=10, verbose_name='Condição')),
                ('item_pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_recebimento', to='compras.itempedidocompra', verbose_name='Item do Pedido')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.recebimentomercadoria', verbose_name='Recebimento')),
            ],
            options={
                'verbose_name': 'Item de Recebimento',
                'verbose_name_plural': 'Itens de Recebimento',
            },
        ),
    ]
